spring:
  application:
    name: hl
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

server:
  tomcat:
    accept-count: 10_000
    max-connections: 100_000
    threads:
      max: 20000
    connection-timeout: 2s

