spring:
  application:
    name: hl
  threads:
    virtual:
      enabled: true

server:
  tomcat:
    accept-count: 10000
    max-connections: 20000
    threads:
      max: 20000
    connection-timeout: 2s
