spring:
  application:
    name: hl
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

server:
  tomcat:
    accept-count: 2000
    max-connections: 5000
    threads:
      max: 300
    connection-timeout: 2s

